### ISSUE TITLE
On Load of User Profile Page Post Gear Modal

### ISSUE THREAD

**Issue by livingstona16** [trescara/gearup-front#15]
The modal form will include an input for the image url, a dropdown labeled "Category", an input labeled "Gear Type", an input labeled "Manufacturer", a text area labeled "Gear Description", an input labeled "Price", a toggle button labeled "Available", and a submit button labeled "Post Gear".  On submit of "Post Gear", the gear card will populate to the list of "Your Gear for Lending".

**Comment by trescara** [comment]
Form completed working on POST functionality

**Comment by livingstona16** [comment]
POST functionality works
