### ISSUE TITLE
On Load of User Profile Page Gear Lended and Edit Button.

### ISSUE THREAD

**Issue by livingstona16** [trescara/gearup-front#16]
On load, a section with a h2 labeled "Your Gear for Lending" and gear cards renders. Each gear card will display the image associated with the type of gear, the gear name, the manufacturer, the description of the gear, the price, the availability status, and a button labeled "Edit". On click of the "Edit" button, a modal form spanning the size of the screen will pop up.

**Comment by trescara** [comment]
Gear loads on user page and edit button has been created. Styling will fall into css work and button is another item. Complete.
