### ISSUE TITLE
Landing Page OnClick - Populating Cards

### ISSUE THREAD

**Issue by livingstona16** [trescara/gearup-front#6]
On click of the category cards, more cards will populate below the category cards. These new cards will be the gear items associated with the selected category. These gear item cards will display the image associated with the type of gear, the gear name, the manufacturer, the description of the gear, the price, the availability status, and a button labeled "Contact now!".

**Comment by trescara** [comment]
Contact now button in the works with other items still to be completed. Currently the page loads on card click populating the current selection of gear. Additional items added to database to test map function.
